# Generated by Django 5.0.3 on 2024-03-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('FR', 'FR'), ('AS', 'AS')], max_length=2),
        ),
    ]
