# Generated by Django 5.0.3 on 2024-03-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('AS', 'AS'), ('FR', 'FR')], max_length=2),
        ),
    ]
