# Generated by Django 5.0.3 on 2024-03-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_organization_org_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('RE', 'RE'), ('IP', 'IP')], default='IP', max_length=2),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('AS', 'AS'), ('FR', 'FR')], default='FR', max_length=2),
        ),
    ]
